src/Admin/CatalogBundle/Entity/Manufacturer.php
<?php

namespace Admin\CatalogBundle\Entity;

use Admin\CatalogBundle\Exception\ChildrenException;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints\NotNull;

/**
 * Class Manufacturers
 * @ORM\Table(name="manufacturers", uniqueConstraints={@UniqueConstraint(name="manufacturer_name_type", columns={"name", "manufacturer_type"})})
 * @ORM\Entity(repositoryClass="Admin\CatalogBundle\Entity\ManufacturerRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(errorPath="name", fields={"name"})
 */
class Manufacturer extends ImageBase
{
    const MANUFACTURER_TYPE_CHEMISTRY = 'chemistry';
    const MANUFACTURER_TYPE_CULTURES = 'cultures';
    const MANUFACTURER_TYPE_SUBSTRATES = 'substrates';
    const MANUFACTURER_TYPE_ENTOMOPHAGES = 'entomophages';

    protected static $img_dir = 'manufacturers';

    public static $logo_size = [
        'width' => 95,
        'height' => 40
    ];

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", nullable=false, unique=true)
     * @NotNull()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="manufacturer_type", type="string", nullable=false, unique=false)
     * @NotNull()
     */
    private $manufacturer_type;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Admin\CatalogBundle\Entity\Provider", mappedBy="manufacturer")
     */
    private $providers;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Admin\CatalogBundle\Entity\CultureManufacturer", mappedBy="manufacturer")
     */
    private $culture_manufacturers;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Admin\CatalogBundle\Entity\Chemistry", mappedBy="manufacturers")
     */
    private $chemistry;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Admin\CatalogBundle\Entity\Entomophage", mappedBy="manufacturers")
     */
    private $entomophages;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Admin\CatalogBundle\Entity\SubstrateCategoryManufacturer", mappedBy="manufacturer")
     */
    private $substrate_category_manufacturers;

    public function __construct() {
        $this->providers = new ArrayCollection();
        $this->culture_manufacturers = new ArrayCollection();
        $this->substrate_category_manufacturers = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Manufacturer
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Manufacturer
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getManufacturerType()
    {
        return $this->manufacturer_type;
    }

    /**
     * @param string $manufacturer_type
     * @return Manufacturer
     */
    public function setManufacturerType($manufacturer_type)
    {
        $this->manufacturer_type = $manufacturer_type;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getProviders()
    {
        return $this->providers;
    }

    /**
     * @param ArrayCollection $providers
     * @return Manufacturer
     */
    public function setProviders($providers)
    {
        $this->providers = $providers;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getCultureManufacturers()
    {
        return $this->culture_manufacturers;
    }

    /**
     * @param ArrayCollection $culture_manufacturers
     * @return Manufacturer
     */
    public function setCultureManufacturers($culture_manufacturers)
    {
        $this->culture_manufacturers = $culture_manufacturers;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getChemistry()
    {
        return $this->chemistry;
    }

    /**
     * @param ArrayCollection $chemistry
     * @return Manufacturer
     */
    public function setChemistry($chemistry)
    {
        $this->chemistry = $chemistry;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getEntomophages()
    {
        return $this->entomophages;
    }

    /**
     * @param ArrayCollection $entomophages
     * @return Manufacturer
     */
    public function setEntomophages($entomophages)
    {
        $this->entomophages = $entomophages;
        return $this;
    }

    /**
     * @ORM\PreRemove()
     */
    public function checkRemove()
    {
        if ($this->providers->count()) {
            throw new ChildrenException();
        }
    }

    public function removeProvider(Provider $provider) {
        $this->providers->removeElement($provider);
    }

    public function addProvider(Provider $provider) {
        $this->providers->add($provider);
    }

    /**
     * @return ArrayCollection
     */
    public function getSubstrateCategoryManufacturers()
    {
        return $this->substrate_category_manufacturers;
    }

    /**
     * @param ArrayCollection $substrate_category_manufacturers
     * @return Manufacturer
     */
    public function setSubstrateCategoryManufacturers($substrate_category_manufacturers)
    {
        $this->substrate_category_manufacturers = $substrate_category_manufacturers;
        return $this;
    }
}

src/Admin/CatalogBundle/Form/ManufacturerType.php
<?php

namespace Admin\CatalogBundle\Form;

use Admin\CatalogBundle\Entity\ImageBase;
use Admin\CatalogBundle\Entity\Manufacturer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Valid;

class ManufacturerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Название'
                ],
                'required' => true,
                'error_bubbling' => true
            ])
            ->add('manufacturer_type', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'choices' => [
                    Manufacturer::MANUFACTURER_TYPE_CHEMISTRY => 'Химия',
                    Manufacturer::MANUFACTURER_TYPE_CULTURES => 'Культуры',
                    Manufacturer::MANUFACTURER_TYPE_ENTOMOPHAGES => 'Энтомофаги',
                    Manufacturer::MANUFACTURER_TYPE_SUBSTRATES => 'Субстраты'
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('providers', 'Symfony\Component\Form\Extension\Core\Type\CollectionType', [
                'entry_type' => ProviderType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'error_bubbling' => true,
                'by_reference' => true,
                'constraints' => new Valid(),
                'required' => false,
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('attachment_data', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                'attr' => [
                    'class' => 'form-control vermin_attachment',
                ],
                'required' => false,
                'mapped' => false
            ])
            ->add('attachment_data2', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                'attr' => [
                    'class' => 'form-control vermin_attachment2',
                ],
                'required' => false,
                'mapped' => false
            ])
            ->add('attachment_data3', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                'attr' => [
                    'class' => 'form-control vermin_attachment3',
                ],
                'required' => false,
                'mapped' => false
            ])
            ->add('attachment_data4', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                'attr' => [
                    'class' => 'form-control vermin_attachment4',
                ],
                'required' => false,
                'mapped' => false
            ])
            ->add('video', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Ссылка на видео'
                ],
                'required' => false,
                'error_bubbling' => true
            ])
            ->add('attachment')
            ->add('attachment2')
            ->add('attachment3')
            ->add('attachment4');

        $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
            /** @var ImageBase $imageBase */
            $imageBase = $event->getData();
            $form = $event->getForm();

            $imgContent = $form->get('attachment_data')->getData();
            $imgContent = preg_replace('/(data\:image\/[a-z]{3,4}\;base64\,)/', '', $imgContent, 1);
            $imgContent = base64_decode($imgContent);

            if ($imgContent) {
                $fPath = '/tmp/' . uniqid(rand(0, 9999), true);
                file_put_contents($fPath, $imgContent);
                $attachment = new File($fPath);
                $imageBase->setAttachment($attachment);
            }

            $imgContent = $form->get('attachment_data2')->getData();
            $imgContent = preg_replace('/(data\:image\/[a-z]{3,4}\;base64\,)/', '', $imgContent, 1);
            $imgContent = base64_decode($imgContent);

            if ($imgContent) {
                $fPath = '/tmp/' . uniqid(rand(0, 9999), true);
                file_put_contents($fPath, $imgContent);
                $attachment = new File($fPath);
                $imageBase->setAttachment2($attachment);
            }

            $imgContent = $form->get('attachment_data3')->getData();
            $imgContent = preg_replace('/(data\:image\/[a-z]{3,4}\;base64\,)/', '', $imgContent, 1);
            $imgContent = base64_decode($imgContent);

            if ($imgContent) {
                $fPath = '/tmp/' . uniqid(rand(0, 9999), true);
                file_put_contents($fPath, $imgContent);
                $attachment = new File($fPath);
                $imageBase->setAttachment3($attachment);
            }

            $imgContent = $form->get('attachment_data4')->getData();
            $imgContent = preg_replace('/(data\:image\/[a-z]{3,4}\;base64\,)/', '', $imgContent, 1);
            $imgContent = base64_decode($imgContent);

            if ($imgContent) {
                $fPath = '/tmp/' . uniqid(rand(0, 9999), true);
                file_put_contents($fPath, $imgContent);
                $attachment = new File($fPath);
                $imageBase->setAttachment4($attachment);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => true,
            'constraints' => new Valid()
        ));
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getBlockPrefix()
    {
        return 'manufacturer';
    }
}

src/Admin/CatalogBundle/Controller/ManufacturerController.php
<?php

namespace Admin\CatalogBundle\Controller;

use Admin\CatalogBundle\Entity\Manufacturer;
use Admin\CatalogBundle\Form\ManufacturerType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Manufacturer API controller.
 *
 * @Route("/admin/catalog/manufacturer")
 */
class ManufacturerController extends DefaultController
{
    /**
     * @Route(
     *     path="/",
     *     name="manufacturer",
     *     methods={"GET"}
     * )
     * @Template("@AdminCatalog/Manufacturer/index.html.twig")
     */
    public function indexAction()
    {
        $manufacturers = $this->getManufacturerRepository()
            ->createQueryBuilder('c')
            ->orderBy('c.name', 'ASC')
            ->getQuery()
            ->getResult();

        return [
            'manufacturers' => $manufacturers
        ];
    }

    /**
     * @Route(
     *     path="/add",
     *     name="manufacturer_add",
     *     methods={"GET", "POST"}
     * )
     * @Template("@AdminCatalog/Manufacturer/edit.html.twig")
     */
    public function addAction()
    {
        $manufacturer = new Manufacturer();

        $form = $this->createForm(ManufacturerType::class, $manufacturer, [
            'error_bubbling' => true
        ]);

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route(
     *     path="/edit/{id}",
     *     name="manufacturer_edit",
     *     methods={"GET", "POST"}
     * )
     * @Template("@AdminCatalog/Manufacturer/edit.html.twig")
     * @param Manufacturer $manufacturer
     * @return array
     */
    public function editAction(Manufacturer $manufacturer)
    {
        return [
            'form' => $this->createForm(ManufacturerType::class, $manufacturer)->createView()
        ];
    }

    /**
     * @Route(
     *     path="/update/{id}",
     *     defaults={"id" = null},
     *     name="manufacturer_update",
     *     methods={"POST"}
     * )
     * @Template("@AdminCatalog/Manufacturer/edit.html.twig")
     * @param Request $request
     * @param Manufacturer $manufacturer
     * @return array
     */
    public function updateAction(Request $request, Manufacturer $manufacturer = null)
    {
        if (!$manufacturer) {
            $manufacturer = new Manufacturer();
        }

        $form = $this->createForm(ManufacturerType::class, $manufacturer);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($manufacturer);
            $em->flush();
        }

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route(
     *     path="/delete/{id}",
     *     name="manufacturer_delete",
     *     methods={"GET", "POST", "DELETE"}
     * )
     * @param Manufacturer $manufacturer
     * @return RedirectResponse
     */
    public function deleteAction(Manufacturer $manufacturer)
    {
        $em = $this->getDoctrine()->getManager();

        $em->remove($manufacturer);
        $em->flush();

        return $this->redirect($this->generateUrl('manufacturer'));
    }
}

src/Admin/CatalogBundle/Resources/views/Manufacturer/edit.html.twig
{% extends app.request.isXmlHttpRequest ? 'AdminClientBundle::ajax.html.twig' : is_granted('IS_AUTHENTICATED_FULLY') ? 'AdminClientBundle::layout.html.twig' : 'AdminClientBundle::default.html.twig' %}

{% block body %}
  {% if form.vars.errors|length == 0 and app.request.method == 'POST' %}
    <script type="text/javascript">
      document.location.reload();
    </script>
  {% else %}
    {% if form.vars.value.id is not null %}
      <form id="edit-client-form" action="{{ path('manufacturer_update', { id: form.vars.value.id }) }}" method="post" enctype="application/x-www-form-urlencoded"
    {% else %}
      <form id="edit-client-form" action="{{ path('manufacturer_update') }}" method="post" enctype="application/x-www-form-urlencoded"
    {% endif %}
    class="form-horizontal">
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Название</label>

      <div class="col-sm-10">
        {{ form_widget(form.name) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Тип</label>

      <div class="col-sm-10">
        {{ form_widget(form.manufacturer_type) }}
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Видео</label>

      <div class="col-sm-10">
        {{ form_widget(form.video) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Фото</label>

      <div class="col-sm-4">
        {{ form_widget(form.attachment) }}
        <div class="hide">{{ form_widget(form.attachment_data) }}</div>
      </div>
      <div class="col-sm-4">
        {{ form_widget(form.attachment2) }}
        <div class="hide">{{ form_widget(form.attachment_data2) }}</div>
      </div>
      <div class="col-sm-4">
        {{ form_widget(form.attachment3) }}
        <div class="hide">{{ form_widget(form.attachment_data3) }}</div>
      </div>
      <div class="col-sm-4">
        {{ form_widget(form.attachment4) }}
        <div class="hide">{{ form_widget(form.attachment_data4) }}</div>
      </div>
    </div>

    <div class="form-group hide">
      <label for="inputEmail3" class="col-sm-2 control-label">Поставщики</label>

      <div class="col-sm-10">
        {{ form_widget(form.providers) }}
      </div>
    </div>




    {{ form_rest(form) }}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        {% if form.vars.value.id is null %}
          <button type="submit" class="btn btn-default">Добавить</button>
        {% else %}
          <button type="submit" class="btn btn-default">Сохранить</button>
        {% endif %}
      </div>
    </div>
    </form>
    {% if form.vars.errors|length %}
      <div class="alert alert-danger">
        {{ form_errors(form) }}
      </div>
    {% endif %}
  {% endif %}
{% endblock %}

src/Admin/CatalogBundle/Resources/views/Manufacturer/index.html.twig
{% extends app.request.isXmlHttpRequest ? 'AdminClientBundle::ajax.html.twig' : is_granted('IS_AUTHENTICATED_FULLY') ? 'AdminClientBundle::layout.html.twig' : 'AdminClientBundle::default.html.twig' %}

{% block body %}

  {% set manufacturer_type = {
  'chemistry': 'Химия',
  'cultures': 'Культуры',
  'substrates': 'Субстраты',
  'entomophages': 'Энтомофаги'
  } %}

  <table class="table table-responsive table-striped table-hover">
    <thead>
    <tr>
      <th>Название</th>
      <th>Тип производителя</th>
      <th>Видео</th>
      <th>Фото</th>
      <th class="text-center">
        <a href="{{ path('manufacturer_add') }}" id="add-vermin-btn" class="btn btn-primary btn-sm">Добавить</a></th>
    </tr>
    </thead>
    <tbody>
    {% for manufacturer in manufacturers %}
      <tr>
        <td>{{ manufacturer.name }}</td>
        <td>{{ manufacturer_type[manufacturer.manufacturerType] }}</td>
        <td>{{ manufacturer.video }}</td>
        <td>{% if manufacturer.image %}
            <a href="/compiled/bundles/admincatalog/images/manufacturers/original/{{ manufacturer.image }}" target="_blank">
              <img src="/compiled/bundles/admincatalog/images/manufacturers/logo/{{ manufacturer.image }}" alt="Фото">
            </a>
          {% endif %}
          {% if manufacturer.image2 %}
            <a href="/compiled/bundles/admincatalog/images/manufacturers/original/{{ manufacturer.image2 }}" target="_blank">
              <img src="/compiled/bundles/admincatalog/images/manufacturers/logo/{{ manufacturer.image2 }}" alt="Фото">
            </a>
          {% endif %}
          {% if manufacturer.image3 %}
            <a href="/compiled/bundles/admincatalog/images/manufacturers/original/{{ manufacturer.image3 }}" target="_blank">
              <img src="/compiled/bundles/admincatalog/images/manufacturers/logo/{{ manufacturer.image3 }}" alt="Фото">
            </a>
          {% endif %}
          {% if manufacturer.image4 %}
            <a href="/compiled/bundles/admincatalog/images/manufacturers/original/{{ manufacturer.image4 }}" target="_blank">
              <img src="/compiled/bundles/admincatalog/images/manufacturers/logo/{{ manufacturer.image4 }}" alt="Фото">
            </a>
          {% endif %}
        </td>
        <td class="text-center">
          <nobr>
            <form id="edit-vermin-btn" style="display: inline-block;" action="{{ path('manufacturer_edit', {id: manufacturer.id}) }}" enctype="application/x-www-form-urlencoded" method="get">
              <button type="submit" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-edit"></span></button>
            </form>
            &nbsp;
            <form style="display: inline-block;" action="{{ path('manufacturer_delete', {id: manufacturer.id}) }}" enctype="application/x-www-form-urlencoded" method="get">
              <button type="submit" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span>
              </button>
            </form>
          </nobr>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div id="modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
        </div>
        <div class="modal-body">
          <p>One fine body&hellip;</p>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock %}