src/Admin/ClientBundle/Entity/Client.php
<?php

namespace Admin\ClientBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\JoinColumn;
use Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Client
 *
 * @ORM\Table(uniqueConstraints={@UniqueConstraint(name="email_uniq", columns={"email"}),@UniqueConstraint(name="token_uniq", columns={"token"})})
 * @ORM\Entity(repositoryClass="Admin\ClientBundle\Entity\ClientRepository")
 * @UniqueEntity("email", message="Email already in use")
 * @UniqueEntity("token", message="Token already in use")
 * @ORM\HasLifecycleCallbacks()
 */
class Client implements UserInterface
{
    const ROLE_USER = 'ROLE_USER';
    const ROLE_ADMIN = 'ROLE_ADMIN';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    private static $user_roles = [
        self::ROLE_USER,
        self::ROLE_ADMIN,
        self::ROLE_SUPER_ADMIN,
    ];

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Assert\NotBlank(message="Email should not be empty")
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     * @ORM\Column(name="email", type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @var string
     *
     * @Assert\NotBlank(message="Password should not be empty")
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="salt", type="string", length=255)
     */
    private $salt;

    /**
     * @var string
     *
     * @Assert\NotBlank(message="Role should not be empty")
     * @ORM\Column(name="role", type="string", length=255)
     */
    private $role;

    /**
     * @var DBRole
     *
     * @Assert\NotBlank(message="DB Role should not be empty")
     * @ManyToOne(targetEntity="DBRole", inversedBy="clients")
     * @JoinColumn(name="db_role_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     **/
    private $db_role;

    /**
     * @var string
     *
     * @ORM\Column(name="token", type="string", length=255, unique=true)
     */
    private $token;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="token_created", type="datetime", length=255)
     */
    private $token_created;

    /**
     * @var string
     *
     * @ORM\Column(name="reg_ip", type="string", length=255)
     */
    private $reg_ip;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="reg_dtm", type="datetime", length=255)
     */
    private $reg_dtm;

    /**
     * @var string
     *
     * @ORM\Column(name="login_ip", type="string", length=255, nullable=true)
     */
    private $login_ip;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="login_dtm", type="datetime", length=255, nullable=true)
     */
    private $login_dtm;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated", type="datetime")
     */
    private $updated;

    private $isPasswordChanged = false;

    public function __construct()
    {
        $this->token = md5(uniqid());
        $this->token_created = new \DateTime();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Client
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @return void
     *
     * @ORM\PreUpdate
     * @ORM\PrePersist
     */
    public function setPasswordSave()
    {
        if ($this->isPasswordChanged) {
            $this->salt = md5(uniqid());
            $encoder = new MessageDigestPasswordEncoder('sha512', true, 10000);
            $this->password = $encoder->encodePassword($this->password, $this->getSalt());
        }
    }

    /**
     * Set password
     *
     * @param string $password
     * @return Client
     */
    public function setPassword($password)
    {
        $this->password = $password;
        $this->isPasswordChanged = true;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param string $salt
     * @return Client
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * @return string
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * Set role
     *
     * @param string $role
     * @return Client
     */
    public function setRole($role)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get role
     *
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * @param DBRole $DBRole
     * @return Client
     */
    public function setDbRole($DBRole)
    {
        $this->db_role = $DBRole;

        return $this;
    }

    /**
     * @return DBRole
     */
    public function getDbRole()
    {
        return $this->db_role;
    }

    /**
     * @param string $token
     * @return Client
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * @param \DateTime $token_created
     * @return Client
     */
    public function setTokenCreated($token_created)
    {
        $this->token_created = $token_created;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getTokenCreated()
    {
        return $this->token_created;
    }

    /**
     * @param \DateTime $login_dtm
     * @return Client
     */
    public function setLoginDtm($login_dtm)
    {
        $this->login_dtm = $login_dtm;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getLoginDtm()
    {
        return $this->login_dtm;
    }

    /**
     * @param string $login_ip
     * @return Client
     */
    public function setLoginIp($login_ip)
    {
        $this->login_ip = $login_ip;

        return $this;
    }

    /**
     * @return string
     */
    public function getLoginIp()
    {
        return $this->login_ip;
    }

    /**
     * @param \DateTime $reg_dtm
     * @return Client
     */
    public function setRegDtm($reg_dtm)
    {
        $this->reg_dtm = $reg_dtm;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getRegDtm()
    {
        return $this->reg_dtm;
    }

    /**
     * @param string $reg_ip
     * @return Client
     */
    public function setRegIp($reg_ip)
    {
        $this->reg_ip = $reg_ip;

        return $this;
    }

    /**
     * @return string
     */
    public function getRegIp()
    {
        return $this->reg_ip;
    }

    /**
     * @ORM\PrePersist()
     *
     * @return Client
     * @throws \Exception
     */
    public function setCreated()
    {
        $this->created = new \DateTime();
        $this->updated = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @ORM\PreUpdate()
     *
     * @return Client
     * @throws \Exception
     */
    public function setUpdated()
    {
        $this->updated = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return string[] The user roles
     */
    public function getRoles()
    {
        return [$this->role];
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function __sleep()
    {
        //return get_object_vars($this);
        return array(
            'id',
            'email',
            'password',
            'salt',
            'reg_ip',
            'reg_dtm',
            'login_ip',
            'login_dtm',
        );
    }

    /**
     * @return array
     */
    public static function getUserRoles()
    {
        return self::$user_roles;
    }

    public function isTokenValid($token)
    {
        return $token === $this->token && abs(date('U') - $this->token_created->getTimestamp()) < 10;
    }

    public function checkAuthentication($password)
    {
        $encoder = new MessageDigestPasswordEncoder('sha512', true, 10000);

src/Admin/ClientBundle/Form/ClientType.php
<?php

namespace Admin\ClientBundle\Form;

use Admin\ClientBundle\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', 'Symfony\Component\Form\Extension\Core\Type\EmailType', [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Email'
                ],
                'required' => true,
                'error_bubbling' => true
            ])
            ->add('password', 'Symfony\Component\Form\Extension\Core\Type\PasswordType', [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Пароль'
                ],
                'required' => true,
                'error_bubbling' => true
            ])
            ->add('db_role', 'Symfony\Bridge\Doctrine\Form\Type\EntityType', [
                'class' => 'Admin\ClientBundle\Entity\DBRole',
                'choice_label' => 'role',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Роль DB'
                ],
                'required' => true,
                'error_bubbling' => true
            ])
            ->add('role', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'choices' => [
                    Client::ROLE_USER => 'Пользователь',
                    Client::ROLE_ADMIN => 'Администратор',
                    Client::ROLE_SUPER_ADMIN => 'Суперадминистратор'
                ],
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Роль DB'
                ],
                'required' => true,
                'error_bubbling' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Admin\ClientBundle\Entity\Client'
        ));
    }

    public function getBlockPrefix()
    {
        return 'admin_clientbundle_clienttype';
    }
}

src/Admin/ClientBundle/Controller/ClientController.php
<?php

namespace Admin\ClientBundle\Controller;

use Admin\ClientBundle\Entity\Client;
use Admin\ClientBundle\Form\ClientType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

/**
 * Auth controller.
 *
 * @Route("/admin/client")
 */
class ClientController extends DefaultController
{
    /**
     * @Route(
     *     path="/",
     *     name="client",
     *     methods={"GET"}
     * )
     * @Template("@AdminClient/Client/index.html.twig")
     */
    public function indexAction()
    {
        $clients = $this->getClientRepository()
            ->createQueryBuilder('c')
            ->orderBy('c.email', 'ASC')
            ->getQuery()
            ->getResult();

        return [
            'clients' => $clients,
        ];
    }

    /**
     * @Route(
     *     path="/delete/{id}",
     *     name="client_delete",
     *     methods={"GET", "POST", "DELETE"}
     * )
     * @ParamConverter("client", class="AdminClientBundle:Client")
     * @param Client $client
     * @return RedirectResponse
     */
    public function deleteAction(Client $client)
    {
        $em = $this->getDoctrine()->getManager();

        $em->remove($client);
        $em->flush();

        return $this->redirect($this->generateUrl('client'));
    }

    /**
     * @Route(
     *     path="/add",
     *     name="client_add",
     *     methods={"GET", "POST"}
     * )
     * @Template("@AdminClient/Client/edit.html.twig")
     */
    public function addAction()
    {
        $client = new Client();

        $form = $this->createForm(ClientType::class, $client, [
                'error_bubbling' => true,
            ]
        );

        return [
            'form' => $form->createView(),
        ];
    }

    /**
     * @Route(
     *     path="/edit/{id}",
     *     name="client_edit",
     *     methods={"GET", "POST"}
     * )
     * @ParamConverter("client", class="AdminClientBundle:Client")
     * @Template("@AdminClient/Client/edit.html.twig")
     * @param Request $request
     * @param Client $client
     * @return array
     */
    public function editAction(Request $request, Client $client)
    {
        return [
            'form' => $this->createForm(ClientType::class, $client)->createView(),
        ];
    }

    /**
     * @Route(
     *     path="/update/{id}",
     *     defaults={"id" = null},
     *     name="client_update",
     *     methods={"POST"}
     * )
     * @ParamConverter("client", class="AdminClientBundle:Client")
     * @Template("@AdminClient/Client/edit.html.twig")
     * @param Request $request
     * @param Client|null $client
     * @return array
     * @throws \Exception
     */
    public function updateAction(Request $request, Client $client = null)
    {
        if (!$client) {
            $client = new Client();
            $client->setRegIp($request->getClientIp());
            $client->setRegDtm(new \DateTime());
        }

        $form = $this->createForm(ClientType::class, $client);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            if ($client->getId()) {
                $em->merge($client);
            } else {
                $em->persist($client);
            }

            $em->flush();
        }

        return [
            'form' => $form->createView(),
        ];
    }
}

src/Admin/ClientBundle/Resources/views/Client/edit.html.twig
{% extends app.request.isXmlHttpRequest ? 'AdminClientBundle::ajax.html.twig' : is_granted('IS_AUTHENTICATED_FULLY') ? 'AdminClientBundle::layout.html.twig' : 'AdminClientBundle::default.html.twig' %}

{% block body %}
  {% if form.vars.errors|length == 0 and app.request.method == 'POST' %}
    <script type="text/javascript">
      document.location.reload();
    </script>
  {% else %}
    {% if form.vars.value.id is not null %}
      <form id="edit-client-form" action="{{ path('client_update', { id: form.vars.value.id }) }}" method="post"
            enctype="application/x-www-form-urlencoded"
    {% else %}
      <form id="edit-client-form" action="{{ path('client_update') }}" method="post" enctype="application/x-www-form-urlencoded"
    {% endif %}
    class="form-horizontal">
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Email</label>

      <div class="col-sm-10">
        {{ form_widget(form.email) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Пароль</label>

      <div class="col-sm-10">
        {{ form_widget(form.password) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Роль DB</label>

      <div class="col-sm-10">
        {{ form_widget(form.db_role) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Роль</label>

      <div class="col-sm-10">
        {{ form_widget(form.role) }}
      </div>
    </div>
    {{ form_rest(form) }}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        {% if form.vars.value.id is null %}
          <button type="submit" class="btn btn-default">Добавить</button>
        {% else %}
          <button type="submit" class="btn btn-default">Сохранить</button>
        {% endif %}
      </div>
    </div>
    </form>
    {% if form.vars.errors|length %}
      <div class="alert alert-danger">
        {{ form_errors(form) }}
      </div>
    {% endif %}
  {% endif %}
{% endblock %}

src/Admin/ClientBundle/Resources/views/Client/index.html.twig
{% extends app.request.isXmlHttpRequest ? 'AdminClientBundle::ajax.html.twig' : is_granted('IS_AUTHENTICATED_FULLY') ? 'AdminClientBundle::layout.html.twig' : 'AdminClientBundle::default.html.twig' %}

{% block body %}

  <table class="table table-responsive table-striped table-hover">
    <thead>
    <tr>
      <th>Email</th>
      <th>Роль</th>
      <th>Зарегестрирован</th>
      <th>Последний логин</th>
      <th>Роль DB</th>
      <th>Домен</th>
      <th class="text-center"><a href="{{ path('client_add') }}" id="add-client-btn" class="btn btn-primary btn-sm">Добавить</a></th>
    </tr>
    </thead>
    <tbody>
    {% for client in clients %}
      <tr>
        <td>{{ client.email }}</td>
        <td>{{ client.role }}</td>
        <td>{{ client.regDtm|date('Y-m-d H:i:s') }}</td>
        <td>{{ client.loginDtm|date('Y-m-d H:i:s') }}</td>
        <td>{{ client.dbRole.role }}</td>
        <td>{{ client.dbRole.domain }}</td>
        <td class="text-center">
          <nobr>
            <form id="edit-client-btn" style="display: inline-block;"
                  action="{{ path('client_edit', {id: client.id}) }}"
                  enctype="application/x-www-form-urlencoded" method="get">
              <button type="submit" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-edit"></span></button>
            </form>&nbsp;
            <form style="display: inline-block;" action="{{ path('client_delete', {id: client.id}) }}"
                  enctype="application/x-www-form-urlencoded" method="get">
              <button type="submit" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span></button>
            </form>
          </nobr>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div id="modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
        </div>
        <div class="modal-body">
          <p>One fine body&hellip;</p>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock %}