src/Admin/CatalogBundle/Entity/Vermin.php
<?php

namespace Admin\CatalogBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping\UniqueConstraint;

/**
 * Class Vermin
 * @ORM\Table(name="vermins", uniqueConstraints={@UniqueConstraint(name="vermin_name", columns={"name"})})
 * @ORM\Entity(repositoryClass="Admin\CatalogBundle\Entity\VerminRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(errorPath="name", fields={"name"})
 */
class Vermin extends ImageBase {

    protected static $img_dir = 'vermin';

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", unique=true, nullable=false)
     * @Assert\NotNull()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="name_en", type="string", unique=true, nullable=true)
     * @Assert\NotNull()
     */
    private $name_en;

    /**
     * @var string
     *
     * @ORM\Column(name="short_name", type="string", unique=false, nullable=true)
     */
    private $short_name;

    /**
     * @var string
     *
     * @ORM\Column(name="short_name_en", type="string", unique=false, nullable=true)
     */
    private $short_name_en;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", unique=false, nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="description_en", type="text", unique=false, nullable=true)
     */
    private $description_en;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description1", type="text", unique=false, nullable=true)
     */
    private $dis_description1;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description1_en", type="text", unique=false, nullable=true)
     */
    private $dis_description1_en;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description2", type="text", unique=false, nullable=true)
     */
    private $dis_description2;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description2_en", type="text", unique=false, nullable=true)
     */
    private $dis_description2_en;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description3", type="text", unique=false, nullable=true)
     */
    private $dis_description3;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description3_en", type="text", unique=false, nullable=true)
     */
    private $dis_description3_en;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description4", type="text", unique=false, nullable=true)
     */
    private $dis_description4;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description4_en", type="text", unique=false, nullable=true)
     */
    private $dis_description4_en;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description5", type="text", unique=false, nullable=true)
     */
    private $dis_description5;

    /**
     * @var string
     *
     * @ORM\Column(name="dis_description5_en", type="text", unique=false, nullable=true)
     */
    private $dis_description5_en;

    /**
     * @var VerminCategory
     *
     * @ORM\ManyToOne(targetEntity="Admin\CatalogBundle\Entity\VerminCategory", inversedBy="vermins")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id", nullable=false)
     * @Assert\NotNull()
     */
    private $category;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Admin\CatalogBundle\Entity\Entomophage", mappedBy="vermins")
     */
    private $entomophages;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Admin\CatalogBundle\Entity\Chemistry", mappedBy="vermins")
     */
    private $chemistry;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Vermin
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Vermin
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getShortName()
    {
        return $this->short_name;
    }

    /**
     * @param string $short_name
     * @return Vermin
     */
    public function setShortName($short_name)
    {
        $this->short_name = $short_name;
        return $this;
    }


    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Vermin
     */
    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return string
     */
    public function getDisDescription1()
    {
        return $this->dis_description1;
    }

    /**
     * @param string $dis_description1
     * @return Vermin
     */
    public function setDisDescription1($dis_description1)
    {
        $this->dis_description1 = $dis_description1;
        return $this;
    }

    /**
     * @return string
     */
    public function getDisDescription2()
    {
        return $this->dis_description2;
    }

    /**
     * @param string $dis_description2
     * @return Vermin
     */
    public function setDisDescription2($dis_description2)
    {
        $this->dis_description2 = $dis_description2;
        return $this;
    }

    /**
     * @return string
     */
    public function getDisDescription3()
    {
        return $this->dis_description3;
    }

    /**
     * @param string $dis_description3
     * @return Vermin
     */
    public function setDisDescription3($dis_description3)
    {
        $this->dis_description3 = $dis_description3;
        return $this;
    }

    /**
     * @return string
     */
    public function getDisDescription4()
    {
        return $this->dis_description4;
    }

    /**
     * @param string $dis_description4
     * @return Vermin
     */
    public function setDisDescription4($dis_description4)
    {
        $this->dis_description4 = $dis_description4;
        return $this;
    }

    /**
     * @return string
     */
    public function getDisDescription5()
    {
        return $this->dis_description5;
    }

    /**
     * @param string $dis_description5
     * @return Vermin
     */
    public function setDisDescription5($dis_description5)
    {
        $this->dis_description5 = $dis_description5;
        return $this;
    }

    /**
     * @return VerminCategory
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param VerminCategory $category
     * @return Vermin
     */
    public function setCategory($category)
    {
        $this->category = $category;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getEntomophages()
    {
        return $this->entomophages;
    }

    /**
     * @param ArrayCollection $entomophages
     * @return Vermin
     */
    public function setEntomophages($entomophages)
    {
        $this->entomophages = $entomophages;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getChemistry()
    {
        return $this->chemistry;
    }

    /**
     * @param ArrayCollection $chemistry
     * @return Vermin
     */
    public function setChemistry($chemistry)
    {
        $this->chemistry = $chemistry;
        return $this;
    }

    /**
     * @return string
     */
    public function getNameEn(): ?string
    {
        return $this->name_en;
    }

    /**
     * @param string $name_en
     */
    public function setNameEn(string $name_en): void
    {
        $this->name_en = $name_en;
    }

    /**
     * @return string
     */
    public function getShortNameEn(): ?string
    {
        return $this->short_name_en;
    }

    /**
     * @param string $short_name_en
     */
    public function setShortNameEn(string $short_name_en): void
    {
        $this->short_name_en = $short_name_en;
    }

    /**
     * @return string
     */
    public function getDescriptionEn(): ?string
    {
        return $this->description_en;
    }

    /**
     * @param string $description_en
     */
    public function setDescriptionEn(string $description_en): void
    {
        $this->description_en = $description_en;
    }

    /**
     * @return string
     */
    public function getDisDescription1En(): ?string
    {
        return $this->dis_description1_en;
    }

    /**
     * @param string $dis_description1_en
     */
    public function setDisDescription1En(string $dis_description1_en): void
    {
        $this->dis_description1_en = $dis_description1_en;
    }

    /**
     * @return string
     */
    public function getDisDescription2En(): ?string
    {
        return $this->dis_description2_en;
    }

    /**
     * @param string $dis_description2_en
     */
    public function setDisDescription2En(string $dis_description2_en): void
    {
        $this->dis_description2_en = $dis_description2_en;
    }

    /**
     * @return string
     */
    public function getDisDescription3En(): ?string
    {
        return $this->dis_description3_en;
    }

    /**
     * @param string $dis_description3_en
     */
    public function setDisDescription3En(string $dis_description3_en): void
    {
        $this->dis_description3_en = $dis_description3_en;
    }

    /**
     * @return string
     */

src/Admin/CatalogBundle/Controller/VerminController.php
<?php

namespace Admin\CatalogBundle\Controller;

use Admin\CatalogBundle\Entity\Vermin;
use Admin\CatalogBundle\Form\VerminType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

/**
 * Vermin controller.
 *
 * @Route("/admin/catalog/vermin")
 */
class VerminController extends DefaultController
{
    /**
     * @Route(
     *     path="/",
     *     name="vermin",
     *     methods={"GET"}
     * )
     * @Template("@AdminCatalog/Vermin/index.html.twig")
     */
    public function indexAction()
    {
        $vermins = $this->getVerminRepository()
            ->createQueryBuilder('c')
            ->orderBy('c.name', 'ASC')
            ->getQuery()
            ->getResult();

        return [
            'vermins' => $vermins
        ];
    }

    /**
     * @Route(
     *     path="/add",
     *     name="vermin_add",
     *     methods={"GET", "POST"}
     * )
     * @Template("@AdminCatalog/Vermin/edit.html.twig")
     */
    public function addAction()
    {
        $vermin = new Vermin();

        $form = $this->createForm(VerminType::class, $vermin, [
            'error_bubbling' => true
        ]);

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route(
     *     path="/edit/{id}",
     *     name="vermin_edit",
     *     methods={"GET", "POST"}
     * )
     * @Template("@AdminCatalog/Vermin/edit.html.twig")
     * @param Vermin $vermin
     * @return array
     */
    public function editAction(Vermin $vermin)
    {
        return [
            'form' => $this->createForm(VerminType::class, $vermin)->createView()
        ];
    }

    /**
     * @Route(
     *     path="/update/{id}",
     *     defaults={"id" = null},
     *     name="vermin_update",
     *     methods={"POST"}
     * )
     * @Template("@AdminCatalog/Vermin/edit.html.twig")
     * @param Request $request
     * @param Vermin $vermin
     * @return array
     */
    public function updateAction(Request $request, Vermin $vermin = null)
    {
        if (!$vermin) {
            $vermin = new Vermin();
        }

        $form = $this->createForm(VerminType::class, $vermin);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($vermin);
            $em->flush();
        }

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route(
     *     path="/delete/{id}",
     *     name="vermin_delete",
     *     methods={"GET", "POST", "DELETE"}
     * )
     * @param Vermin $vermin
     * @return RedirectResponse
     */
    public function deleteAction(Vermin $vermin)
    {
        $em = $this->getDoctrine()->getManager();

        $em->remove($vermin);
        $em->flush();

        return $this->redirect($this->generateUrl('vermin'));
    }
}

src/Admin/CatalogBundle/Resources/views/Vermin/edit.html.twig
{% extends app.request.isXmlHttpRequest ? 'AdminClientBundle::ajax.html.twig' : is_granted('IS_AUTHENTICATED_FULLY') ? 'AdminClientBundle::layout.html.twig' : 'AdminClientBundle::default.html.twig' %}

{% block body %}
  {% if form.vars.errors|length == 0 and app.request.method == 'POST' %}
    <script type="text/javascript">
      document.location.reload();
    </script>
  {% else %}
    {% if form.vars.value.id is not null %}
      <form id="edit-client-form" action="{{ path('vermin_update', { id: form.vars.value.id }) }}" method="post" enctype="application/x-www-form-urlencoded"
    {% else %}
      <form id="edit-client-form" action="{{ path('vermin_update') }}" method="post" enctype="application/x-www-form-urlencoded"
    {% endif %}
    class="form-horizontal">
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Категория</label>

      <div class="col-sm-10">
        {{ form_widget(form.category) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Название</label>

      <div class="col-sm-5">
        {{ form_widget(form.name) }}
      </div>
      <div class="col-sm-5">
        {{ form_widget(form.name_en) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Сокращение</label>

      <div class="col-sm-5">
        {{ form_widget(form.short_name) }}
      </div>
      <div class="col-sm-5">
        {{ form_widget(form.short_name_en) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Описание</label>

      <div class="col-sm-5">
        {{ form_widget(form.description) }}
      </div>
      <div class="col-sm-5">
        {{ form_widget(form.description_en) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">
        <span class="vermin-lights pull-right">
          <span class="light"><span class="blue-light"></span></span>
        </span>
      </label>

      <div class="col-sm-5">
        {{ form_widget(form.dis_description1) }}
      </div>
      <div class="col-sm-5">
        {{ form_widget(form.dis_description1_en) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">
        <span class="vermin-lights pull-right">
          <span class="light"><span class="green-light"></span></span>
        </span>
      </label>

      <div class="col-sm-5">
        {{ form_widget(form.dis_description2) }}
      </div>
      <div class="col-sm-5">
        {{ form_widget(form.dis_description2_en) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">
        <span class="vermin-lights pull-right">
          <span class="light"><span class="yellow-light"></span></span>
        </span>
      </label>

      <div class="col-sm-5">
        {{ form_widget(form.dis_description3) }}
      </div>
      <div class="col-sm-5">
        {{ form_widget(form.dis_description3_en) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">
        <span class="vermin-lights pull-right">
          <span class="light"><span class="orange-light"></span></span>
        </span>
      </label>

      <div class="col-sm-5">
        {{ form_widget(form.dis_description4) }}
      </div>
      <div class="col-sm-5">
        {{ form_widget(form.dis_description4_en) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">
        <span class="vermin-lights pull-right">
          <span class="light"><span class="red-light"></span></span>
        </span>
      </label>

      <div class="col-sm-5">
        {{ form_widget(form.dis_description5) }}
      </div>
      <div class="col-sm-5">
        {{ form_widget(form.dis_description5_en) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Видео</label>

      <div class="col-sm-10">
        {{ form_widget(form.video) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Фото</label>

      <div class="col-sm-4">
        {{ form_widget(form.attachment) }}
        <div class="hide">{{ form_widget(form.attachment_data) }}</div>
      </div>
      <div class="col-sm-4">
        {{ form_widget(form.attachment2) }}
        <div class="hide">{{ form_widget(form.attachment_data2) }}</div>
      </div>
      <div class="col-sm-4">
        {{ form_widget(form.attachment3) }}
        <div class="hide">{{ form_widget(form.attachment_data3) }}</div>
      </div>
      <div class="col-sm-4">
        {{ form_widget(form.attachment4) }}
        <div class="hide">{{ form_widget(form.attachment_data4) }}</div>
      </div>
    </div>





    {{ form_rest(form) }}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        {% if form.vars.value.id is null %}
          <button type="submit" class="btn btn-default">Добавить</button>
        {% else %}
          <button type="submit" class="btn btn-default">Сохранить</button>
        {% endif %}
      </div>
    </div>
    </form>
    {% if form.vars.errors|length %}
      <div class="alert alert-danger">
        {{ form_errors(form) }}
      </div>
    {% endif %}
  {% endif %}
{% endblock %}

src/Admin/CatalogBundle/Resources/views/Vermin/index.html.twig
{% extends app.request.isXmlHttpRequest ? 'AdminClientBundle::ajax.html.twig' : is_granted('IS_AUTHENTICATED_FULLY') ? 'AdminClientBundle::layout.html.twig' : 'AdminClientBundle::default.html.twig' %}

{% block body %}

  <div class="text-right">
    <a href="{{ path('vermin_add') }}" id="add-vermin-btn" class="btn btn-primary btn-sm">Добавить</a>
  </div>

  {% for vermin in vermins %}
  <div class="content-element">
    <div class="ref-content-name">
      <div class="name-ru">
        <strong>{{ vermin.category.name }}</strong>: {{ vermin.name }} {% if vermin.shortName %}{{ '(' ~ vermin.shortName ~ ')' }}{% endif %}
        <form id="edit-vermin-btn" style="display: inline-block;" action="{{ path('vermin_edit', {id: vermin.id}) }}" enctype="application/x-www-form-urlencoded" method="get">
          <span class="glyphicon glyphicon-edit text-info"></span>
        </form>&nbsp;
        <form style="display: inline-block;" action="{{ path('vermin_delete', {id: vermin.id}) }}" enctype="application/x-www-form-urlencoded" method="get">
          <span class="glyphicon glyphicon-remove text-danger"></span>
        </form>
      </div>
    </div>
    <div class="img-content">
      {% if vermin.image %}
        <a href="/compiled/bundles/admincatalog/images/vermin/original/{{ vermin.image }}" target="_blank">
          <img src="/compiled/bundles/admincatalog/images/vermin/logo/{{ vermin.image }}" alt="Фото" class="ref-content-img">
        </a>
      {% else %}
        <img src="/compiled/bundles/adminclient/images/no_photo_small.png" alt="Фото" class="ref-content-img">
      {% endif %}
      {% if vermin.image2 %}
        <a href="/compiled/bundles/admincatalog/images/vermin/original/{{ vermin.image2 }}" target="_blank">
          <img src="/compiled/bundles/admincatalog/images/vermin/logo/{{ vermin.image2 }}" alt="Фото" class="ref-content-img">
        </a>
      {% else %}
        <img src="/compiled/bundles/adminclient/images/no_photo_small.png" alt="Фото" class="ref-content-img">
      {% endif %}
      {% if vermin.image3 %}
        <a href="/compiled/bundles/admincatalog/images/vermin/original/{{ vermin.image3 }}" target="_blank">
          <img src="/compiled/bundles/admincatalog/images/vermin/logo/{{ vermin.image3 }}" alt="Фото" class="ref-content-img">
        </a>
      {% else %}
        <img src="/compiled/bundles/adminclient/images/no_photo_small.png" alt="Фото" class="ref-content-img">
      {% endif %}
      {% if vermin.image4 %}
        <a href="/compiled/bundles/admincatalog/images/vermin/original/{{ vermin.image4 }}" target="_blank">
          <img src="/compiled/bundles/admincatalog/images/vermin/logo/{{ vermin.image4 }}" alt="Фото" class="ref-content-img">
        </a>
      {% else %}
        <img src="/compiled/bundles/adminclient/images/no_photo_small.png" alt="Фото" class="ref-content-img">
      {% endif %}
    </div>
    <div class="ref-content-descr">{{ vermin.description }}</div>

    <div class="clear"></div>

    <div class="vermin-labels">
      <div class="vermin-labels-name"><strong>{{ 'Пороги вредоносности' }}</strong></div>
      <div>
        <div class="vermin-lights">
          <div class="light"><span class="blue-light"></span></div>
          <div class="vermin-lights-descr">{% if vermin.disDescription1 %}{{ vermin.disDescription1 }}{% else %}{{ 'Данных нет' }}{% endif %}</div>
        </div>
        <div class="vermin-lights">
          <div class="light"><span class="green-light"></span></div>
          <div class="vermin-lights-descr">{% if vermin.disDescription2 %}{{ vermin.disDescription2 }}{% else %}{{ 'Данных нет' }}{% endif %}</div>
        </div>
        <div class="vermin-lights">
          <div class="light"><span class="yellow-light"></span></div>
          <div class="vermin-lights-descr">{% if vermin.disDescription3 %}{{ vermin.disDescription3 }}{% else %}{{ 'Данных нет' }}{% endif %}</div>
        </div>
        <div class="vermin-lights">
          <div class="light"><span class="orange-light"></span></div>
          <div class="vermin-lights-descr">{% if vermin.disDescription4 %}{{ vermin.disDescription4 }}{% else %}{{ 'Данных нет' }}{% endif %}</div>
        </div>
        <div class="vermin-lights">
          <div class="light"><span class="red-light"></span></div>
          <div class="vermin-lights-descr">{% if vermin.disDescription5 %}{{ vermin.disDescription5 }}{% else %}{{ 'Данных нет' }}{% endif %}</div>
        </div>
      </div>
    </div>

    <div class="clear"></div>

    <div class="vermin-labels">
      <div class="vermin-labels-name"><strong>{{ 'Видео' }}</strong></div>
      <div>
        {% if vermin.video %}
        <a href="{{ 'https://www.youtube.com/embed/' ~ vermin.video }}" target="_blank">
          {{ 'https://www.youtube.com/embed/' ~ vermin.video }}
        </a>
        {% else %}
            {{ 'Ссылка не указана' }}
        {% endif %}
      </div>
    </div>

    <div class="end-border"></div>
  </div>
  {% endfor %}


  <div id="modal" class="modal fade">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
        </div>
        <div class="modal-body">
          <p>One fine body&hellip;</p>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock %}