src/Admin/CatalogBundle/Entity/SubstrateCategoryManufacturer.php
<?php

namespace Admin\CatalogBundle\Entity;

use Admin\CatalogBundle\Exception\ChildrenException;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping\UniqueConstraint;

/**
 * Class SubstrateCategoryManufacturer
 * @ORM\Table(name="substrate_category_manufacturers", uniqueConstraints={@UniqueConstraint(name="substrate_category_manufacturer", columns={"substrate_category_id", "manufacturer_id"})})
 * @ORM\Entity(repositoryClass="Admin\CatalogBundle\Entity\SubstrateCategoryManufacturerRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"substrate_category", "manufacturer"},
 *  errorPath="manufacturer",
 *  message="This substrate category already have given manufacturer"
 * )
 */
class SubstrateCategoryManufacturer extends CUBase {
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var SubstrateCategory
     *
     * @ORM\ManyToOne(targetEntity="Admin\CatalogBundle\Entity\SubstrateCategory", inversedBy="substrate_category_manufacturers")
     * @ORM\JoinColumn(name="substrate_category_id", referencedColumnName="id", nullable=false)
     * @Assert\NotNull()
     */
    private $substrate_category;

    /**
     * @var Manufacturer
     *
     * @ORM\ManyToOne(targetEntity="Admin\CatalogBundle\Entity\Manufacturer", inversedBy="substrate_category_manufacturers")
     * @ORM\JoinColumn(name="manufacturer_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
     * @Assert\NotNull()
     */
    private $manufacturer;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Admin\CatalogBundle\Entity\Substrate", mappedBy="substrate_category_manufacturer")
     */
    private $substrates;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return SubstrateCategoryManufacturer
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return SubstrateCategory
     */
    public function getSubstrateCategory()
    {
        return $this->substrate_category;
    }

    /**
     * @param SubstrateCategory $substrate_category
     * @return SubstrateCategoryManufacturer
     */
    public function setSubstrateCategory($substrate_category)
    {
        $this->substrate_category = $substrate_category;
        return $this;
    }

    /**
     * @return Manufacturer
     */
    public function getManufacturer()
    {
        return $this->manufacturer;
    }

    /**
     * @param Manufacturer $manufacturer
     * @return SubstrateCategoryManufacturer
     */
    public function setManufacturer($manufacturer)
    {
        $this->manufacturer = $manufacturer;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getSubstrates()
    {
        return $this->substrates;
    }

    /**
     * @param ArrayCollection $substrates
     * @return SubstrateCategoryManufacturer
     */
    public function setSubstrates($substrates)
    {
        $this->substrates = $substrates;
        return $this;
    }

    /**
     * @ORM\PreRemove()
     */
    public function checkRemove()
    {
        if ($this->substrates->count()) {
            throw new ChildrenException();
        }
    }

}

src/Admin/CatalogBundle/Form/SubstrateCategoryManufacturerType.php
<?php

namespace Admin\CatalogBundle\Form;

use Admin\CatalogBundle\Entity\CultureRepository;
use Admin\CatalogBundle\Entity\Manufacturer;
use Admin\CatalogBundle\Entity\ManufacturerRepository;
use Admin\CatalogBundle\Entity\SubstrateCategoryRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SubstrateCategoryManufacturerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('substrate_category', 'Symfony\Bridge\Doctrine\Form\Type\EntityType', [
                'class' => 'Admin\CatalogBundle\Entity\SubstrateCategory',
                'query_builder' => function (SubstrateCategoryRepository $repo) {
                    return $repo->createQueryBuilder('sc')
                        ->orderBy('sc.name', 'ASC');
                },
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('manufacturer', 'Symfony\Bridge\Doctrine\Form\Type\EntityType', [
                'class' => 'Admin\CatalogBundle\Entity\Manufacturer',
                'query_builder' => function (ManufacturerRepository $repo) {
                    return $repo->createQueryBuilder('m')
                        ->orderBy('m.name', 'ASC')
                        ->where('m.manufacturer_type = :manufacturer_type')
                        ->setParameter('manufacturer_type', Manufacturer::MANUFACTURER_TYPE_SUBSTRATES);
                },
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'form-control',
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => true
        ));
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getBlockPrefix()
    {
        return 'substrate_category_manufacturer';
    }
}

src/Admin/CatalogBundle/Controller/SubstrateCategoryManufacturerController.php
<?php

namespace Admin\CatalogBundle\Controller;

use Admin\CatalogBundle\Entity\SubstrateCategoryManufacturer;
use Admin\CatalogBundle\Form\SubstrateCategoryManufacturerType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * SubstrateCategoryManufacturer API controller.
 *
 * @Route("/admin/catalog/substrate-manufacturer")
 */
class SubstrateCategoryManufacturerController extends DefaultController
{
    /**
     * @Route(
     *     path="/",
     *     name="substrate_manufacturer",
     *     methods={"GET"}
     * )
     * @Template("@AdminCatalog/SubstrateCategoryManufacturer/index.html.twig")
     */
    public function indexAction()
    {
        $substrates = $this->getSubstrateCategoryManufacturerRepository()
            ->createQueryBuilder('c')
            ->orderBy('c.id', 'ASC')
            ->getQuery()
            ->getResult();

        return [
            'substrate_categories' => $substrates
        ];
    }

    /**
     * @Route(
     *     path="/add",
     *     name="substrate_manufacturer_add",
     *     methods={"GET", "POST"}
     * )
     * @Template("@AdminCatalog/SubstrateCategoryManufacturer/edit.html.twig")
     */
    public function addAction()
    {
        $substrate_manufacturer = new SubstrateCategoryManufacturer();

        $form = $this->createForm(SubstrateCategoryManufacturerType::class, $substrate_manufacturer, [
            'error_bubbling' => true
        ]);

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route(
     *     path="/edit/{id}",
     *     name="substrate_manufacturer_edit",
     *     methods={"GET", "POST"}
     * )
     * @Template("@AdminCatalog/SubstrateCategoryManufacturer/edit.html.twig")
     * @param SubstrateCategoryManufacturer $substrate_manufacturer
     * @return array
     */
    public function editAction(SubstrateCategoryManufacturer $substrate_manufacturer)
    {
        return [
            'form' => $this->createForm(SubstrateCategoryManufacturerType::class, $substrate_manufacturer)->createView()
        ];
    }

    /**
     * @Route(
     *     path="/update/{id}",
     *     defaults={"id" = null},
     *     name="substrate_manufacturer_update",
     *     methods={"POST"}
     * )
     * @Template("@AdminCatalog/SubstrateCategoryManufacturer/edit.html.twig")
     * @param Request $request
     * @param SubstrateCategoryManufacturer $substrate_manufacturer
     * @return array
     */
    public function updateAction(Request $request, SubstrateCategoryManufacturer $substrate_manufacturer = null)
    {
        if (!$substrate_manufacturer) {
            $substrate_manufacturer = new SubstrateCategoryManufacturer();
        }

        $form = $this->createForm(SubstrateCategoryManufacturerType::class, $substrate_manufacturer);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($substrate_manufacturer);
            $em->flush();
        }

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route(
     *     path="/delete/{id}",
     *     name="substrate_manufacturer_delete",
     *     methods={"GET", "POST", "DELETE"}
     * )
     * @param SubstrateCategoryManufacturer $substrate_manufacturer
     * @return RedirectResponse
     */
    public function deleteAction(SubstrateCategoryManufacturer $substrate_manufacturer)
    {
        $em = $this->getDoctrine()->getManager();

        $em->remove($substrate_manufacturer);
        $em->flush();

        return $this->redirect($this->generateUrl('substrate_manufacturer'));
    }
}

src/Admin/CatalogBundle/Resources/views/SubstrateCategoryManufacturer/edit.html.twig
{% extends app.request.isXmlHttpRequest ? 'AdminClientBundle::ajax.html.twig' : is_granted('IS_AUTHENTICATED_FULLY') ? 'AdminClientBundle::layout.html.twig' : 'AdminClientBundle::default.html.twig' %}

{% block body %}
  {% if form.vars.errors|length == 0 and app.request.method == 'POST' %}
    <script type="text/javascript">
      document.location.reload();
    </script>
  {% else %}
    {% if form.vars.value.id is not null %}
      <form id="edit-client-form" action="{{ path('substrate_manufacturer_update', { id: form.vars.value.id }) }}" method="post"
            enctype="application/x-www-form-urlencoded"
    {% else %}
      <form id="edit-client-form" action="{{ path('substrate_manufacturer_update') }}" method="post" enctype="application/x-www-form-urlencoded"
    {% endif %}
    class="form-horizontal">
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Категория</label>

      <div class="col-sm-10">
        {{ form_widget(form.substrate_category) }}
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Производ.</label>

      <div class="col-sm-10">
        {{ form_widget(form.manufacturer) }}
      </div>
    </div>



    {{ form_rest(form) }}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        {% if form.vars.value.id is null %}
          <button type="submit" class="btn btn-default">Добавить</button>
        {% else %}
          <button type="submit" class="btn btn-default">Сохранить</button>
        {% endif %}
      </div>
    </div>
    </form>
    {% if form.vars.errors|length %}
      <div class="alert alert-danger">
        {{ form_errors(form) }}
      </div>
    {% endif %}
  {% endif %}
{% endblock %}

src/Admin/CatalogBundle/Resources/views/SubstrateCategoryManufacturer/index.html.twig
{% extends app.request.isXmlHttpRequest ? 'AdminClientBundle::ajax.html.twig' : is_granted('IS_AUTHENTICATED_FULLY') ? 'AdminClientBundle::layout.html.twig' : 'AdminClientBundle::default.html.twig' %}

{% block body %}

  <table class="table table-responsive table-striped table-hover">
    <thead>
    <tr>
      <th>Категория</th>
      <th>Производитель</th>
      <th class="text-center"><a href="{{ path('substrate_manufacturer_add') }}" id="add-vermin-btn" class="btn btn-primary btn-sm">Добавить</a></th>
    </tr>
    </thead>
    <tbody>
    {% for sm in substrate_categories %}
      <tr>
        <td>{{ sm.substrateCategory.name }}</td>
        <td>{{ sm.manufacturer.name }}</td>
        <td class="text-center">
          <nobr>
            <form id="edit-vermin-btn" style="display: inline-block;"
                  action="{{ path('substrate_manufacturer_edit', {id: sm.id}) }}"
                  enctype="application/x-www-form-urlencoded" method="get">
              <button type="submit" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-edit"></span></button>
            </form>&nbsp;
            <form style="display: inline-block;" action="{{ path('substrate_manufacturer_delete', {id: sm.id}) }}"
                  enctype="application/x-www-form-urlencoded" method="get">
              <button type="submit" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span></button>
            </form>
          </nobr>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div id="modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
        </div>
        <div class="modal-body">
          <p>One fine body&hellip;</p>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock %}